### ISSUE TITLE
Image / banner not loaded

### ISSUE THREAD

**Issue by jeremyrich** [charlesthk/django-simple-mail#12]
Hello !

Mail sending and context works super well ! 

But I have trubble with the template. I am using the default one but I don't manage to get logo and banner displayed in my email ! 
![image](https://user-images.githubusercontent.com/30413040/98248546-61f4cd00-1f75-11eb-9270-b85f0130f294.png)

I have setup as written in the guide : 
SIMPLE_MAIL_USE_CKEDITOR = True
SIMPLE_MAIL_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'

media settings : 
STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
MEDIA_ROOT = os.path.join(BASE_DIR, "static/images")
MEDIA_URL = "/images/"
CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_BASEPATH = "/static/ckeditor/ckeditor/"

Config:
django-simple-mail 2.3.3.
django  2.2

**Comment by jeremyrich** [comment]
When overriding template, using same default template as you but adding a src="real image path" like https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png   it's working ... but that really not convenient

**Comment by charlesthk** [comment]
@jeremyrich thanks for your feedback.

You can update your `MEDIA_URL` to include your full URL like `https://example.com/images/` and it should work.

**Comment by jeremyrich** [comment]
I don't really understand your point as MEDIA_URL is then pass to the view like this : 

from django.conf.urls.static import static

urlpatterns = [
...,
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

**Comment by charlesthk** [comment]
@jeremyrich the snippet you gave is for development and not production.

To include an image or a banner in your emails you need to make them publicly accessible. That is the reason why an absolute url should be given.
