### ISSUE TITLE
Remove CSS Warnging

### ISSUE THREAD

**Issue by Jufik** [charlesthk/django-simple-mail#4]
CSS Utils logs CSS warnings, wich is a nighthmare with a TDD approach.
Using this: https://gist.github.com/texuf/1e1ef7fce7aaa67caf4d solves the issue

I'm adding a LOG_CSS in settings, which will patch CSS Utils in apps.py.

**Comment by charlesthk** [comment]
Closed with PR #5 thanks @Jufik for your issue and PR.
