### ISSUE TITLE
Using with AnyMail

### ISSUE THREAD

**Issue by amitjindal** [charlesthk/django-simple-mail#8]
Hi, Thanks for this excellent package.

I was wondering if this works with https://github.com/anymail/django-anymail
We use CookieCutter-Django and have Anymail pretty integrated in our application. It will be great if this can work with Anymail.

Thanks
Amit

**Comment by charlesthk** [comment]
@amitjindal quoting Django-Anymail documentation :

> the regular Django email functions `send_mail` will send through your chosen ESP

Simple mail relies on Django's `send_mail` so I guess it should perfectly work.
